name: Tests

on: [ push ]

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Container
        uses: docker/build-push-action@v5
        with:
          tags: project-image
          context: .
          push: false
          outputs: type=docker,dest=/tmp/project.tar
          build-args: |
            KEY=value

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: project
          path: /tmp/project.tar



  tests-cocotb:
    name: cocotb tests
    runs-on: ubuntu-latest
    needs: [ build-image ]
    steps:
      - name: Download image
        uses: actions/download-artifact@v3
        with:
          name: project
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/project.tar

      - name: Checkout sources
        uses: actions/checkout@v4
        with: 
          submodules: true

      - name: Run cocotb tests
        uses: addnab/docker-run-action@v3
        with:
          image: project-image
          options: -v ${{ github.workspace }}:/work --workdir /work
          run: |
            pytest -s ./baseband/test/
