name: Tests

on: [ push ]

jobs:
  tests-cocotb:
    name: cocotb tests
    runs-on: ubuntu-latest
    container: ghcr.io/zaporozhets/image_build_and_push:main
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with: 
          submodules: true

      - name: Run cocotb tests
        run: pytest -s ./baseband/test/
